export const workbenchClient = String.raw`
const root=document.querySelector('#app');
const base=document.querySelector('meta[name="wsrt-base-path"]')?.content||'';
const mutable=document.querySelector('meta[name="wsrt-mutations"]')?.content==='true';
const routes=['overview','architecture','projects','nodes','files','impact','validation','runtime','operations','diagnostics','artifacts','sessions','settings'];
const groups=[['Workspace',['overview','architecture','projects','nodes','files']],['Intelligence',['impact','validation','artifacts']],['Runtime',['runtime','operations','diagnostics','sessions']],['System',['settings']]];
const symbols={overview:'⌂',architecture:'◇',projects:'▦',nodes:'□',files:'≡',impact:'↗',validation:'✓',runtime:'▷',operations:'↻',diagnostics:'!',artifacts:'▱',sessions:'⌁',settings:'⚙'};
const state={data:null,route:'overview',connected:false,stale:false,selected:null,selectedType:null,detail:null,palette:false,drawer:false,collapsed:localStorage.getItem('wsrt.workbench.sidebar')==='collapsed',theme:localStorage.getItem('wsrt.workbench.theme')||'system',query:'',filter:'',impact:null,validation:null,graph:null,busy:false,error:null};
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const unwrap=value=>value&&typeof value==='object'&&'result' in value?value.result:value;
const description=()=>unwrap(state.data?.description)||{};
const snapshot=()=>state.data?.snapshot||{};
const nodes=()=>description().nodes||[];
const projects=()=>description().projects||[];
const title=value=>value.charAt(0).toUpperCase()+value.slice(1);
function setTheme(){const dark=state.theme==='dark'||(state.theme==='system'&&matchMedia('(prefers-color-scheme: dark)').matches);document.documentElement.classList.toggle('dark',dark)}
async function api(request){const response=await fetch(base+'/api/request',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(request)});const body=await response.json();if(!response.ok)throw new Error(body.error?.message||'Request failed');return body}
async function bootstrap(){try{const response=await fetch(base+'/api/bootstrap');if(!response.ok)throw new Error('Workbench bootstrap failed');state.data=await response.json();state.connected=true;state.stale=false;state.error=null;render()}catch(error){state.connected=false;state.error=String(error);render();setTimeout(bootstrap,2000)}}
function currentRoute(){const path=location.pathname.slice(base.length).replace(/^\/+|\/+$/g,'').split('/')[0];return routes.includes(path)?path:'overview'}
function navigate(route,replace=false){state.route=routes.includes(route)?route:'overview';state.drawer=false;const path=base+'/'+(state.route==='overview'?'':state.route);history[replace?'replaceState':'pushState']({},'',path);render()}
function entityCounts(){return nodes().reduce((all,node)=>(all[node.kind]=(all[node.kind]||0)+1,all),{})}
function health(){return nodes().filter(node=>node.health&&['degraded','unhealthy'].includes(node.health.state)).length}
function activeOps(){return (state.data?.operations||[]).filter(operation=>['pending','running'].includes(operation.status)).length}
function shellPage(){const page=pageContent();const inspect=state.selected?inspector():'';return '<div class="shell '+(state.collapsed?'collapsed ':'')+(state.drawer?'drawer ':'')+'"><a class="skip" href="#main">Skip to content</a><div class="mobile-scrim" data-action="drawer-close"></div>'+sidebar()+'<div class="workspace">'+topbar()+'<div class="content-grid '+(state.selected?'inspecting':'')+'"><main id="main" tabindex="-1">'+(!state.connected&&state.data?'<div class="banner">Connection interrupted. Showing revision '+esc(description().workspaceRevision)+' while reconnecting.</div>':'')+(state.stale?'<div class="banner">Workspace revision changed. Refreshing authoritative results…</div>':'')+(state.error?'<div class="banner">'+esc(state.error)+'</div>':'')+page+'</main>'+inspect+'</div>'+statusbar()+'</div>'+mobilePalette()+'</div>'}
function sidebar(){return '<aside class="sidebar" aria-label="Primary navigation"><div class="brand"><span class="brand-mark">W</span><span class="brand-copy"><b>WSRT</b><small>Workbench</small></span><button class="icon collapse" data-action="collapse" aria-label="Collapse navigation">‹</button></div><nav>'+groups.map(group=>'<section class="nav-group"><h2>'+group[0]+'</h2>'+group[1].map(route=>'<a class="nav" href="'+base+'/'+(route==='overview'?'':route)+'" data-route="'+route+'" '+(state.route===route?'aria-current="page"':'')+'><span class="nav-symbol">'+symbols[route]+'</span><span class="nav-label">'+title(route)+'</span></a>').join('')+'</section>').join('')+'</nav><div class="connection '+(state.connected?'online':'')+'"><i></i><span>'+(state.connected?'Connected · r'+esc(description().workspaceRevision):'Reconnecting…')+'</span></div></aside>'}
function topbar(){return '<header class="topbar"><button class="icon menu" data-action="drawer-open" aria-label="Open navigation">☰</button><div class="breadcrumbs"><small>'+esc(description().workspace?.name||'Workspace')+' / '+esc(state.route)+'</small><b>'+title(state.route)+'</b></div><button class="search-trigger" data-action="palette"><span>Search workspace or run a command</span><kbd>Ctrl K</kbd></button><div class="top-actions"><span class="pill '+(health()?'warn':'good')+'">'+(health()?health()+' need attention':'Healthy')+'</span><button class="icon" data-action="theme" aria-label="Change theme">◐</button></div></header>'}
function statusbar(){return '<footer class="statusbar"><span style="color:'+(state.connected?'var(--good)':'var(--bad)')+'">● '+(state.connected?'Authoritative':'Offline')+'</span><span>Protocol '+esc(state.data?.handshake?.protocolVersion||state.data?.started?.metadata?.protocolVersion||2)+'</span><span>Revision '+esc(description().workspaceRevision||snapshot().revision||'—')+'</span><span>'+activeOps()+' active operations</span><span class="spacer"></span><span>'+esc(state.selected||description().workspace?.name||'No workspace')+'</span></footer>'}
function heading(name,copy,actions=''){return '<header class="page-head"><div><span class="eyebrow">WSRT Workbench</span><h1>'+esc(name)+'</h1><p>'+esc(copy)+'</p></div><div class="actions">'+actions+'</div></header>'}
function pageContent(){if(!state.data)return '<div class="empty">Loading authoritative workspace data…</div>';switch(state.route){case'overview':return overview();case'architecture':return architecture();case'projects':return projectPage();case'nodes':return nodesPage();case'files':return filesPage();case'impact':return impactPage();case'validation':return validationPage();case'runtime':return runtimePage();case'operations':return operationsPage();case'diagnostics':return diagnosticsPage();case'artifacts':return artifactsPage();case'sessions':return sessionsPage();case'settings':return settingsPage();default:return overview()}}
function overview(){const d=description(),counts=entityCounts(),caps=d.capabilities||[],important=unwrap(state.data.started)?.importantNodeIds||[];return heading('Understand this workspace','Identity, semantic architecture, capabilities, runtime health, and current activity at revision '+d.workspaceRevision+'.','<button class="button" data-action="refresh">Refresh</button>')+'<div class="overview-grid"><div><section class="surface identity"><div class="surface-pad"><span class="eyebrow">Authoritative workspace</span><h2>'+esc(d.workspace?.name)+'</h2><p class="mono">'+esc(d.workspace?.root)+'</p></div><div class="facts"><div class="fact"><small>Revision</small><b>'+esc(d.workspaceRevision)+'</b></div><div class="fact"><small>Generated</small><b>'+esc(new Date(d.generatedAt).toLocaleTimeString())+'</b></div><div class="fact"><small>Package manager</small><b>'+esc(d.workspace?.packageManager||'Unknown')+'</b></div></div></section><section class="section" style="margin-top:18px"><div class="section-title"><h2>Semantic model</h2><a data-route="nodes" href="'+base+'/nodes">Explore nodes</a></div><div class="surface kind-list">'+Object.entries(counts).sort((a,b)=>b[1]-a[1]).map(entry=>'<div class="kind"><span>'+esc(entry[0])+'</span><b>'+entry[1]+'</b></div>').join('')+'</div></section><section class="section"><div class="section-title"><h2>Important applications and services</h2></div><div class="surface"><ul class="compact-list">'+(important.length?important: nodes().filter(n=>['application','service'].includes(n.kind)).slice(0,6).map(n=>n.id)).map(id=>{const n=nodes().find(item=>item.id===id)||{id,name:id,kind:'node'};return entityRow(n)}).join('')+'</ul></div></section></div><div><section class="section"><div class="section-title"><h2>Capabilities</h2><span class="tag">'+caps.length+' declared</span></div><div class="surface"><ul class="compact-list">'+caps.map(cap=>'<li><span class="dot '+(cap.available?'healthy':'unhealthy')+'"></span><span class="grow"><b>'+esc(cap.id)+'</b><small>'+(cap.available?'Available':esc(cap.details?.support||'Unavailable'))+'</small></span><span class="tag '+(cap.available?'available':'unavailable')+'">'+(cap.available?'available':'unavailable')+'</span></li>').join('')+'</ul></div></section><section class="section"><div class="section-title"><h2>Live state</h2></div><div class="surface kind-list"><div class="kind"><span>Running nodes</span><b>'+nodes().filter(n=>n.lifecycleState==='running').length+'</b></div><div class="kind"><span>Active operations</span><b>'+activeOps()+'</b></div><div class="kind"><span>Health attention</span><b>'+health()+'</b></div><div class="kind"><span>Diagnostics</span><b>'+diagnostics().length+'</b></div></div></section></div></div>'}
function entityRow(n){return '<li data-entity="'+esc(n.id)+'" data-type="node" tabindex="0"><span class="dot '+esc(n.lifecycleState||n.health?.state||'')+'"></span><span class="grow"><b>'+esc(n.name||n.id)+'</b><small>'+esc(n.kind)+' · '+esc(n.id)+'</small></span><span class="tag">'+esc(n.projectId||'workspace')+'</span></li>'}
function toolbar(placeholder,extra=''){return '<div class="toolbar"><input class="field grow" data-input="filter" value="'+esc(state.filter)+'" placeholder="'+esc(placeholder)+'" aria-label="Filter results">'+extra+'</div>'}
function filtered(items){const query=state.filter.toLowerCase();return query?items.filter(item=>JSON.stringify(item).toLowerCase().includes(query)):items}
function projectPage(){const items=filtered(projects());return heading('Projects','Packages and project boundaries, ownership, tasks, artifacts, dependencies, and declared evidence.')+toolbar('Filter projects by name, ID, or root')+'<div class="table-wrap"><table><thead><tr><th>Project</th><th>Kind</th><th>Root</th><th>Visibility</th><th>Evidence</th></tr></thead><tbody>'+items.map(p=>'<tr data-entity="'+esc(p.id)+'" data-type="project"><td><b>'+esc(p.name)+'</b><small class="mono">'+esc(p.id)+'</small></td><td><span class="tag">'+esc(p.kind)+'</span></td><td class="mono">'+esc(p.root)+'</td><td>'+(p.private?'Private':p.publishable?'Publishable':'Unspecified')+'</td><td>'+esc(p.evidence?.length||0)+'</td></tr>').join('')+'</tbody></table></div>'}
function nodesPage(){const items=filtered(nodes());return heading('Nodes','The central semantic explorer for direct and aggregate applications, services, processes, tasks, and artifacts.')+toolbar('Filter canonical ID, alias, kind, project, state…','<select class="field" data-input="kind"><option value="">All kinds</option>'+[...new Set(nodes().map(n=>n.kind))].map(k=>'<option>'+esc(k)+'</option>').join('')+'</select>')+'<div class="table-wrap"><table><thead><tr><th>Node</th><th>Kind</th><th>Project</th><th>Lifecycle</th><th>Health</th><th>Files</th></tr></thead><tbody>'+items.slice(0,300).map(n=>'<tr data-entity="'+esc(n.id)+'" data-type="node"><td><b>'+esc(n.name)+'</b><small class="mono">'+esc(n.canonicalId||n.id)+'</small></td><td><span class="tag">'+esc(n.kind)+'</span></td><td>'+esc(n.projectId||'—')+'</td><td><span class="dot '+esc(n.lifecycleState)+'"></span> '+esc(n.lifecycleState||'unknown')+'</td><td>'+esc(n.health?.state||'unknown')+'</td><td>'+esc(n.files?.length||0)+'</td></tr>').join('')+'</tbody></table></div>'}
async function loadArchitecture(){const roots=(state.filter?nodes().filter(n=>JSON.stringify(n).toLowerCase().includes(state.filter.toLowerCase())):nodes().filter(n=>['application','service'].includes(n.kind))).slice(0,8).map(n=>n.id);if(!roots.length)return;state.busy=true;render();try{state.graph=unwrap(await api({type:'workspace.graph.query',query:{roots,direction:'both',depth:2,limit:120}}))}catch(e){state.error=String(e)}state.busy=false;render()}
function architecture(){const graph=state.graph||{nodes:nodes().filter(n=>['application','service','process'].includes(n.kind)).slice(0,30),relationships:description().relationships?.slice(0,80)||[]};const cols=4;return heading('Architecture','Bounded, query-driven graph slices distinguish containment, dependencies, production, validation, and readiness.','<button class="button" data-action="graph-load">Query graph slice</button>')+toolbar('Focus by application, service, process, or canonical ID')+'<div class="graph" aria-label="Workspace architecture graph"><div class="graph-canvas">'+(graph.relationships||[]).map(edge=>edgeLine(edge,graph.nodes,cols)).join('')+(graph.nodes||[]).map((n,i)=>'<button class="graph-node" style="left:'+(35+(i%cols)*185)+'px;top:'+(32+Math.floor(i/cols)*100)+'px" data-entity="'+esc(n.id)+'" data-type="node"><span class="eyebrow">'+esc(n.kind)+'</span><b>'+esc(n.name)+'</b><small>'+esc(n.id)+'</small></button>').join('')+'</div></div><p class="empty">Showing '+(graph.nodes||[]).length+' nodes'+(graph.truncated?' · result truncated by protocol':'')+'. Focus and query to avoid rendering the entire workspace.</p>'}
function edgeLine(edge,items,cols){const a=items.findIndex(n=>n.id===edge.from),b=items.findIndex(n=>n.id===edge.to);if(a<0||b<0)return'';const x1=119+(a%cols)*185,y1=71+Math.floor(a/cols)*100,x2=119+(b%cols)*185,y2=71+Math.floor(b/cols)*100,dx=x2-x1,dy=y2-y1,len=Math.sqrt(dx*dx+dy*dy),angle=Math.atan2(dy,dx)*180/Math.PI;return '<div class="edge" style="left:'+x1+'px;top:'+y1+'px;width:'+len+'px;transform:rotate('+angle+'deg)"><span>'+esc(edge.kind)+'</span></div>'}
async function queryFiles(){state.busy=true;render();try{const result=unwrap(await api({type:'workspace.files.query',query:{paths:state.filter?[state.filter]:undefined,includeGenerated:true,includePatterns:true,aggregate:true,limit:300}}));state.files=result}catch(e){state.error=String(e)}state.busy=false;render()}
function filesPage(){const files=state.files?.files||nodes().flatMap(n=>n.files||[]).filter((file,index,all)=>all.findIndex(other=>other.path===file.path&&other.ownerId===file.ownerId)===index).slice(0,300);return heading('Semantic file ownership','Declared exact paths and patterns with roles, direct and aggregate owners, confidence, producers, consumers, warnings, and evidence.','<button class="button primary" data-action="files-query">Query ownership</button>')+toolbar('Enter a workspace-relative path or filter declared associations')+(state.files?.support?'<div class="banner">Ownership support: '+esc(state.files.support)+(state.files.unresolvedPatterns?.length?' · '+state.files.unresolvedPatterns.length+' unresolved patterns':'')+'</div>':'')+'<div class="table-wrap"><table><thead><tr><th>Path or pattern</th><th>Match</th><th>Role</th><th>Owner</th><th>Generated</th><th>Confidence</th></tr></thead><tbody>'+filtered(files).map(f=>'<tr data-entity="'+esc(f.path)+'" data-type="file"><td class="mono">'+esc(f.path)+'</td><td><span class="tag '+(f.match==='exact'?'available':'partial')+'">'+esc(f.match)+'</span></td><td>'+esc(f.role)+'</td><td class="mono">'+esc(f.ownerId||f.owners?.join(', '))+'</td><td>'+(f.generated?'Generated':'Declared')+'</td><td>'+esc(f.confidence)+'</td></tr>').join('')+'</tbody></table></div>'}
async function analyze(kind){const paths=state.query.split(/[\n,]/).map(s=>s.trim()).filter(Boolean);if(!paths.length)return;state.busy=true;render();try{const result=unwrap(await api({type:kind==='impact'?'workspace.change.impact':'workspace.validation.recommend',query:{paths,expand:['nodes','projects','tasks','artifacts','files','evidence']}}));state[kind]=result;if(kind==='impact'&&!state.validation)state.query=paths.join('\n')}catch(e){state.error=String(e)}state.busy=false;render()}
function pathForm(action,label){return '<div class="toolbar"><textarea class="field grow" style="height:62px;padding-top:8px" data-input="paths" placeholder="apps/desktop/vite.config.ts\npackages/example/src/index.ts">'+esc(state.query)+'</textarea><button class="button primary" data-action="'+action+'" '+(state.busy?'disabled':'')+'>'+label+'</button></div>'}
function impactPage(){const impact=state.impact;return heading('Change impact','Classified, evidence-backed impact for one or more workspace-relative paths. No filesystem scan or source inference is performed.')+pathForm('impact-analyze','Analyze impact')+(!impact?'<div class="surface empty">Enter changed paths to reveal direct owners, composite parents, runtime dependants, validation tasks, artifacts, and related entities.</div>':'<div class="banner">Support: '+esc(impact.support)+' · confidence: '+esc(impact.confidence)+' · revision '+esc(impact.workspaceRevision)+'</div><div class="impact-groups">'+['direct-owner','composite-parent','dependent-runtime','validation-task','produced-artifact','potentially-affected','related'].map(rel=>{const items=impact.entities.filter(e=>e.relationship===rel);return items.length?'<section class="impact-group"><h3>'+esc(rel.replaceAll('-',' '))+' · '+items.length+'</h3><ul class="compact-list">'+items.map(e=>'<li data-entity="'+esc(e.id)+'" data-type="node"><span class="dot '+(e.direct?'healthy':'')+'"></span><span class="grow"><b>'+esc(e.name)+'</b><small>'+esc(e.reason)+'</small></span><span class="tag">'+esc(e.confidence)+'</span></li>').join('')+'</ul></section>':''}).join('')+'</div><div class="actions" style="margin-top:14px"><button class="button" data-action="impact-copy">Copy structured output</button><button class="button primary" data-route="validation">Open validation</button></div>')}
function validationPage(){const plan=state.validation;return heading('Validation planning','Ordered validation tasks, prerequisites, reasons, evidence, and explicit execution. Nothing runs automatically.')+pathForm('validation-analyze','Plan validation')+(!plan?'<div class="surface empty">Select changed paths to create a deterministic, evidence-backed validation plan.</div>':'<div class="banner">Plan-only mode · '+esc(plan.support)+' support · revision '+esc(plan.workspaceRevision)+'</div><div class="validation-flow">'+plan.recommendations.map(r=>'<div class="validation-step" data-entity="'+esc(r.taskId)+'" data-type="node"><span class="eyebrow">Validation task</span><b>'+esc(r.taskId)+'</b><p>'+esc(r.reason)+'</p><span class="tag">'+esc(r.confidence)+'</span></div>').join('')+'</div><div class="actions" style="margin-top:14px">'+(mutable&&plan.recommendations.length?'<button class="button primary" data-action="validation-execute">Execute selected tasks…</button>':'<span class="tag unavailable">Execution unavailable</span>')+'</div>')}
function runtimePage(){const live=nodes().filter(n=>n.runtime||n.lifecycleState);return heading('Runtime','Current lifecycle, health, readiness, providers, processes, ports, URLs, and safe planning controls.')+'<div class="table-wrap"><table><thead><tr><th>Runtime node</th><th>State</th><th>Health</th><th>Provider</th><th>PID</th><th>Endpoints</th></tr></thead><tbody>'+live.map(n=>'<tr data-entity="'+esc(n.id)+'" data-type="node"><td><b>'+esc(n.name)+'</b><small class="mono">'+esc(n.id)+'</small></td><td><span class="dot '+esc(n.lifecycleState)+'"></span> '+esc(n.lifecycleState||n.runtime?.state||'unknown')+'</td><td>'+esc(n.health?.state||'unknown')+'</td><td>'+esc(n.runtime?.provider||n.providerMetadata?.provider||'—')+'</td><td>'+esc(n.runtime?.processId||'—')+'</td><td>'+esc([...(n.providerMetadata?.urls||[]),...(n.providerMetadata?.ports||[])].join(', ')||'—')+'</td></tr>').join('')+'</tbody></table></div>'}
function operationsPage(){const operations=state.data.operations||[];return heading('Operations','Active and recent authoritative operations with target, progress, correlation, diagnostics, and cancellation state.')+'<div class="surface">'+(operations.length?'<ul class="compact-list">'+operations.slice().reverse().map(o=>'<li data-entity="'+esc(o.id)+'" data-type="operation"><span class="dot '+esc(o.status)+'"></span><span class="grow"><b>'+esc(o.type||o.command?.type||o.id)+'</b><small>'+esc(o.id)+' · '+esc(o.status)+' · '+esc(o.createdAt||'')+'</small></span><span class="tag">'+esc(o.progress??o.status)+'</span></li>').join('')+'</ul>':'<div class="empty">No operations have been recorded. This is a valid idle workspace state.</div>')+'</div>'}
function diagnostics(){const value=state.data?.diagnostics;return Array.isArray(value)?value:Array.isArray(value?.diagnostics)?value.diagnostics:snapshot().diagnostics||[]}
function diagnosticsPage(){const items=filtered(diagnostics());return heading('Diagnostics','Severity, source, entity, code, evidence, and related operation. An empty result is healthy, not an error.')+toolbar('Search message, code, source, entity…')+'<div class="surface">'+(items.length?'<ul class="compact-list">'+items.map(d=>'<li data-entity="'+esc(d.id||d.code||d.message)+'" data-type="diagnostic"><span class="dot '+(d.severity==='error'?'unhealthy':d.severity==='warning'?'degraded':'healthy')+'"></span><span class="grow"><b>'+esc(d.message)+'</b><small>'+esc(d.code||'diagnostic')+' · '+esc(d.source||d.nodeId||'workspace')+'</small></span><span class="tag">'+esc(d.severity||'info')+'</span></li>').join('')+'</ul>':'<div class="empty">No diagnostics at this revision.</div>')+'</div>'}
function artifactsPage(){const artifacts=state.data.artifacts||nodes().filter(n=>n.kind==='artifact');return heading('Artifacts','Declared and confirmed generated artifacts with producer, owner, consumers, paths, related tasks, and evidence.')+'<div class="table-wrap"><table><thead><tr><th>Artifact</th><th>Kind</th><th>Location</th><th>Producer</th><th>Availability</th></tr></thead><tbody>'+artifacts.map(a=>'<tr data-entity="'+esc(a.id)+'" data-type="artifact"><td><b>'+esc(a.name||a.id)+'</b><small class="mono">'+esc(a.id)+'</small></td><td>'+esc(a.kind||a.type||'artifact')+'</td><td class="mono">'+esc(a.path||a.location||a.providerMetadata?.outputPatterns?.join(', ')||'Declared')+'</td><td>'+esc(a.producerId||a.producer||'—')+'</td><td><span class="tag '+(a.available?'available':'partial')+'">'+(a.available?'confirmed':'declared')+'</span></td></tr>').join('')+'</tbody></table></div>'}
function sessionsPage(){const h=state.data.handshake||{},s=state.data.status||{};return heading('Session','Authoritative workspace host, transport, protocol, revision, capabilities, subscriptions, and reconnect state.')+'<div class="overview-grid"><section class="surface surface-pad"><span class="eyebrow">Authoritative host</span><h2>'+esc(h.workspaceId||description().workspace?.id)+'</h2><dl>'+detailRows({Session:h.sessionId||s.sessionId,Protocol:h.protocolVersion||2,Revision:description().workspaceRevision,Transport:h.endpoint?.kind||s.transport||'workspace session',Connected:state.connected?'yes':'reconnecting',Uptime:s.uptime||s.uptimeMs})+'</dl></section><section class="surface surface-pad"><span class="eyebrow">Discovery and permissions</span><dl>'+detailRows({Capabilities:(description().capabilities||[]).length,Subscriptions:'workspace events',Authority:'workspace host',Secrets:'not exposed'})+'</dl></section></div>'}
function settingsPage(){return heading('Settings','Local presentation preferences. These do not mutate authoritative workspace state.')+'<section class="surface surface-pad"><div class="details"><h3>Appearance</h3><label>Theme <select class="field" data-input="theme"><option value="system" '+(state.theme==='system'?'selected':'')+'>System</option><option value="light" '+(state.theme==='light'?'selected':'')+'>Light</option><option value="dark" '+(state.theme==='dark'?'selected':'')+'>Dark</option></select></label></div><div class="details"><h3>Transport and safety</h3><dl>'+detailRows({Mutations:mutable?'Enabled with confirmation':'Read only',Reconnect:'Automatic SSE',StaleRevisions:'Detected and refreshed',Graph:'Bounded query slices'})+'</dl></div><button class="button danger" data-action="layout-reset">Reset local layout</button></section>'}
function detailRows(record){return Object.entries(record).map(entry=>'<div class="detail-row"><dt>'+esc(entry[0])+'</dt><dd>'+esc(entry[1]??'—')+'</dd></div>').join('')}
async function openEntity(id,type){state.selected=id;state.selectedType=type;state.detail=null;render();try{if(type==='node'||type==='artifact')state.detail=unwrap(await api({type:type==='artifact'?'workspace.artifact.describe':'workspace.node.describe',nodeId:id,options:{aggregate:true,depth:2,include:['children','relationships']}}));else if(type==='file')state.detail=unwrap(await api({type:'workspace.file.owners',path:id}));else state.detail=findLocal(id,type)}catch(e){state.detail={id,error:String(e)}}render()}
function findLocal(id,type){const lists={project:projects(),operation:state.data.operations||[],diagnostic:diagnostics()};return (lists[type]||[]).find(item=>item.id===id||item.code===id||item.message===id)||{id}}
function inspector(){const d=state.detail;if(!d)return '<aside class="inspector" aria-label="Context inspector"><div class="inspector-head"><div><b>'+esc(state.selected)+'</b><small>Loading authoritative detail…</small></div><button class="icon" data-action="inspector-close" aria-label="Close inspector">×</button></div><div class="boot" style="height:180px"><i></i></div></aside>';const files=d.files||d.files?.files||[],evidence=d.evidence||[];return '<aside class="inspector" aria-label="Context inspector"><div class="inspector-head"><div><b>'+esc(d.name||d.id||state.selected)+'</b><small>'+esc(d.kind||state.selectedType)+' · '+esc(d.canonicalId||state.selected)+'</small></div><button class="icon" data-action="inspector-close" aria-label="Close inspector">×</button></div><div class="inspector-body">'+(d.error?'<div class="banner">'+esc(d.error)+'</div>':'')+'<section class="details"><h3>Summary</h3><dl>'+detailRows({CanonicalID:d.canonicalId||d.id||state.selected,Kind:d.kind||state.selectedType,Project:d.projectId,Parent:d.parentId,Lifecycle:d.lifecycleState,Health:d.health?.state,Aliases:d.aliases?.join(', ')})+'</dl></section>'+(d.providerMetadata?'<section class="details"><h3>Provider and runtime</h3><dl>'+detailRows({Provider:d.providerMetadata.provider,Runtime:d.runtime?.runtime,PID:d.runtime?.processId,Entrypoints:d.providerMetadata.entrypoints?.join(', '),Configuration:d.providerMetadata.configurationFiles?.join(', '),URLs:d.providerMetadata.urls?.join(', '),Ports:d.providerMetadata.ports?.join(', ')})+'</dl></section>':'')+'<section class="details"><h3>Implementation and files</h3>'+(files.length?'<ul class="compact-list">'+files.slice(0,30).map(f=>'<li data-entity="'+esc(f.path)+'" data-type="file"><span class="grow"><b class="mono">'+esc(f.path)+'</b><small>'+esc(f.role)+' · '+esc(f.match)+' · '+esc(f.confidence)+'</small></span></li>').join('')+'</ul>':'<p class="empty">No declared file associations.</p>')+'</section><section class="details"><h3>Operations</h3><div class="actions">'+(d.operations||[]).map(o=>'<button class="button" data-plan="'+esc(o.type)+'" data-target="'+esc(d.id)+'" '+(!o.available?'disabled':'')+'>'+esc(o.type)+'</button>').join('')+'</div></section><section><h3>Evidence</h3>'+(evidence.length?evidence.map(e=>'<article class="evidence"><span class="tag">'+esc(e.type)+'</span><b> '+esc(e.source)+'</b><p>'+esc(e.reason)+'</p><small class="mono">'+esc(e.file||'workspace configuration')+(e.line?':'+e.line:'')+'</small></article>').join(''):'<p class="empty">No evidence records on this detail.</p>')+'</section></div></aside>'}
function searchItems(){const q=state.query.toLowerCase();const entities=[...nodes().map(n=>({id:n.id,label:n.name,type:n.kind,route:'nodes'})),...projects().map(p=>({id:p.id,label:p.name,type:'project',route:'projects'})),...nodes().flatMap(n=>(n.files||[]).map(f=>({id:f.path,label:f.path,type:'file',route:'files'}))),...(state.data.operations||[]).map(o=>({id:o.id,label:o.type||o.id,type:'operation',route:'operations'})),...diagnostics().map(d=>({id:d.id||d.code,label:d.message,type:'diagnostic',route:'diagnostics'}))];const commands=routes.map(r=>({id:r,label:'Go to '+title(r),type:'command',route:r}));return [...commands,...entities].filter(item=>!q||JSON.stringify(item).toLowerCase().includes(q)).slice(0,80)}
function mobilePalette(){if(!state.palette)return'';return '<div class="palette" data-action="palette-close"><div class="palette-box" role="dialog" aria-label="Workspace search and command palette"><input data-input="palette-query" value="'+esc(state.query)+'" placeholder="Search canonical IDs, names, files, operations…" autofocus><div class="palette-results">'+searchItems().map(item=>'<button class="palette-item" data-palette-id="'+esc(item.id)+'" data-palette-type="'+esc(item.type)+'" data-palette-route="'+esc(item.route)+'"><b>'+esc(item.label)+'</b><small>'+esc(item.type)+' · '+esc(item.id)+'</small></button>').join('')+'</div></div></div>'}
async function planOperation(action,target){try{const command=action==='run'?{type:'tasks.run',ids:[target]}:{type:'nodes.'+action,ids:[target]};const plan=unwrap(await api({type:'workspace.command.plan',command,permissions:['commands.plan']}));if(!confirm('Plan '+action+' for '+target+'?\n\nRisk: '+plan.risk+'\nExecution order: '+plan.executionOrder.join(' → ')+'\nWarnings: '+(plan.warnings.join(', ')||'none')))return;if(!mutable)return alert('Workbench is read only.');await api({type:'workspace.command.execute',command,permissions:plan.requiredPermissions});alert('Operation submitted to authoritative workspace host.')}catch(e){alert(String(e))}}
root.addEventListener('click',event=>{const el=event.target.closest('[data-action],[data-route],[data-entity],[data-palette-id],[data-plan]');if(!el)return;const action=el.dataset.action;if(el.dataset.route){event.preventDefault();navigate(el.dataset.route);return}if(el.dataset.entity){openEntity(el.dataset.entity,el.dataset.type);return}if(el.dataset.paletteId){state.palette=false;navigate(el.dataset.paletteRoute);if(el.dataset.paletteType!=='command')openEntity(el.dataset.paletteId,el.dataset.paletteType);return}if(el.dataset.plan){planOperation(el.dataset.plan,el.dataset.target);return}if(action==='collapse'){state.collapsed=!state.collapsed;localStorage.setItem('wsrt.workbench.sidebar',state.collapsed?'collapsed':'expanded');render()}if(action==='drawer-open'){state.drawer=true;render()}if(action==='drawer-close'){state.drawer=false;render()}if(action==='palette'){state.palette=true;state.query='';render();setTimeout(()=>root.querySelector('[data-input="palette-query"]')?.focus())}if(action==='palette-close'&&event.target===el){state.palette=false;render()}if(action==='inspector-close'){state.selected=null;state.detail=null;render()}if(action==='theme'){state.theme=state.theme==='system'?'light':state.theme==='light'?'dark':'system';localStorage.setItem('wsrt.workbench.theme',state.theme);setTheme();render()}if(action==='refresh')bootstrap();if(action==='graph-load')loadArchitecture();if(action==='files-query')queryFiles();if(action==='impact-analyze')analyze('impact');if(action==='validation-analyze')analyze('validation');if(action==='impact-copy')navigator.clipboard.writeText(JSON.stringify(state.impact,null,2));if(action==='validation-execute'){if(confirm('Execute the recommended validation tasks?'))state.validation.recommendations.forEach(r=>planOperation('run',r.taskId))}if(action==='layout-reset'){localStorage.removeItem('wsrt.workbench.sidebar');state.collapsed=false;render()}});
root.addEventListener('input',event=>{const type=event.target.dataset.input;if(type==='filter'){state.filter=event.target.value;render()}if(type==='paths'){state.query=event.target.value}if(type==='palette-query'){state.query=event.target.value;render()}if(type==='theme'){state.theme=event.target.value;localStorage.setItem('wsrt.workbench.theme',state.theme);setTheme();render()}});
document.addEventListener('keydown',event=>{if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='k'){event.preventDefault();state.palette=!state.palette;state.query='';render()}if(event.key==='Escape'){state.palette=false;state.selected=null;render()}});
addEventListener('popstate',()=>{state.route=currentRoute();render()});
function connectEvents(){const events=new EventSource(base+'/api/events');events.addEventListener('connected',()=>{state.connected=true;render()});events.addEventListener('workspace',event=>{const value=JSON.parse(event.data);state.connected=true;if(value.type==='snapshot.updated'){state.stale=true;bootstrap()}});events.onerror=()=>{state.connected=false;render()}}
function render(){setTheme();root.innerHTML=shellPage()}
state.route=currentRoute();setTheme();bootstrap().then(connectEvents);
`;
